In [2]:
import numpy as np

In [3]:
arr = np.array([[10, 20, 30, 40],
                [50, 60, 70, 80],
                [90, 100, 110, 120]])

print(arr)

[[ 10  20  30  40]
 [ 50  60  70  80]
 [ 90 100 110 120]]


Extracting second row

In [4]:
second_row = arr[1]
print(second_row)


[50 60 70 80]


Extracting first two rows and the second two columns

In [5]:
colmn_row = arr[0:2, 2:4]
print(colmn_row)


[[30 40]
 [70 80]]


Extracting last column using slicing

In [6]:
last_column = arr[:, -1]
print(last_column)


[ 40  80 120]


Replacing middle row 

In [7]:
arr[1] = [1, 2, 3, 4]
print(arr)


[[ 10  20  30  40]
 [  1   2   3   4]
 [ 90 100 110 120]]
