In [25]:
import numpy as np 

In [26]:
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

print(A)


[[1 2 3]
 [4 5 6]
 [7 8 9]]


(a) Scalar broadcasting

In [27]:
scalar_add = A + 10
print("After adding 10:\n", scalar_add)
print("\nShape:", scalar_add.shape)

#[[1+10, 2+10, 3+10],
# [4+10, 5+10, 6+10],
# [7+10, 8+10, 9+10]]


After adding 10:
 [[11 12 13]
 [14 15 16]
 [17 18 19]]

Shape: (3, 3)


(b) Row broadcasting

In [28]:
row = np.array([1, 2, 3])
row_add = A + row
print("After adding row vector:\n", row_add)
print("\nShape:", row_add.shape)

# [[1+1, 2+2, 3+3],
# [4+1, 5+2, 6+3],
# [7+1, 8+2, 9+3]]


After adding row vector:
 [[ 2  4  6]
 [ 5  7  9]
 [ 8 10 12]]

Shape: (3, 3)


(c) Column broadcasting

In [29]:
col = np.array([[1],
                [2], 
                [3]])
col_add = A + col

print("After adding column vector:\n", col_add)
print("\nShape:", col_add.shape)

#[[1+1, 2+1, 3+1],
# [4+2, 5+2, 6+2],
# [7+3, 8+3, 9+3]]


After adding column vector:
 [[ 2  3  4]
 [ 6  7  8]
 [10 11 12]]

Shape: (3, 3)
