In [13]:
import numpy as np

1(a) Zero Matrix (4x4)

In [14]:
zero_matrix = np.zeros((4, 4))
print(zero_matrix)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


1(b) One Matrix (3x2)

In [15]:
one_matrix = np.ones((3, 2))
print(one_matrix)

[[1. 1.]
 [1. 1.]
 [1. 1.]]


1(c) Identity Matrix (5x5)

In [16]:
identity_matrix = np.eye(5)
print(identity_matrix)


[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]
 [0. 0. 0. 1. 0.]
 [0. 0. 0. 0. 1.]]


1(d) Constant Value Array (filled with 7)

In [17]:
constant_array = np.full((3, 3), 7)
print(constant_array)


[[7 7 7]
 [7 7 7]
 [7 7 7]]


1(e) Random Integer Array (3x4)

In [18]:
random_array = np.random.randint(10, 100, size=(3, 4))
print(random_array)


[[44 97 81 26]
 [36 89 47 10]
 [31 60 99 77]]


2. np.arange()

In [20]:
arr = np.arange(5, 50, 5)
print("\nArray from 5 to 50 with step 5:")
print(arr)

reshaped_arr = arr.reshape(3, 3)
print("\nReshaped Array (3x3):")
print(reshaped_arr)



Array from 5 to 50 with step 5:
[ 5 10 15 20 25 30 35 40 45]

Reshaped Array (3x3):
[[ 5 10 15]
 [20 25 30]
 [35 40 45]]
