In [1]:
import numpy as np

1: Create and Reshape an Array

In [2]:
arr = np.arange(1, 13)
print(arr)

[ 1  2  3  4  5  6  7  8  9 10 11 12]


In [ ]:
arr_3x4 = arr.reshape(3, 4)
print("Reshaped into (3x4):\n", arr_3x4)

arr_2x6 = arr.reshape(2, 6)
print("\nReshaped into (2x6):\n", arr_2x6)


Reshaped into (3x4):
 [[ 1  2  3  4]
 [ 5  6  7  8]
 [ 9 10 11 12]]

Reshaped into (2x6):
 [[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]


2: Flatten and Ravel

In [4]:
arr = np.array([[1, 2, 3],
                [4, 5, 6]])

print(arr)

[[1 2 3]
 [4 5 6]]


In [10]:
flat = arr.flatten()
rav = arr.ravel()

print("Flattened Array:\n", flat)
print("Raveled Array:\n", rav)

# Modifying 
flat[0] = 100
rav[1] = 200
print("---------------------------")

print("After Modifying Flatten and Ravel:")
print("Flattened Array:", flat)
print("Raveled Array:", rav)
print("---------------------------")
print("Original Array after modification:\n", arr)


Flattened Array:
 [  1 200   3   4   5   6]
Raveled Array:
 [  1 200   3   4   5   6]
---------------------------
After Modifying Flatten and Ravel:
Flattened Array: [100 200   3   4   5   6]
Raveled Array: [  1 200   3   4   5   6]
---------------------------
Original Array after modification:
 [[  1 200   3]
 [  4   5   6]]


Step # 3

In [12]:
arr = np.arange(1, 10).reshape(3, 3)
print(arr)

[[1 2 3]
 [4 5 6]
 [7 8 9]]


In [18]:
flat_arr = arr.flatten()
ravel_arr = arr.ravel()

print("\nFlattened Array:\n", flat_arr)
print("Raveled Array:\n", ravel_arr)
print("--------------------------------")

# Modifying
flat_arr[0] = 999
ravel_arr[1] = 888

print("Flattened Array:", flat_arr)
print("Raveled Array:", ravel_arr)
print("--------------------------------")
print("Array after changes:\n", arr)



Flattened Array:
 [  1 888   3   4   5   6   7   8   9]
Raveled Array:
 [  1 888   3   4   5   6   7   8   9]
--------------------------------
Flattened Array: [999 888   3   4   5   6   7   8   9]
Raveled Array: [  1 888   3   4   5   6   7   8   9]
--------------------------------
Array after changes:
 [[  1 888   3]
 [  4   5   6]
 [  7   8   9]]
