In [1]:
import numpy as np

 1. Creating 1D and 2D array

In [20]:
arr1 = np.arange(1, 11)
print("1D array: ", arr1)
print("----------------------")
arr2 = np.arange(1, 10).reshape(3, 3)
print("2D array: ")
print(arr2)

1D array:  [ 1  2  3  4  5  6  7  8  9 10]
----------------------
2D array: 
[[1 2 3]
 [4 5 6]
 [7 8 9]]


2. Display

In [21]:
# For 1D array

print("Dimensions:", arr1.ndim)
print("Shape:", arr1.shape)
print("Size:", arr1.size)
print("Data Type:", arr1.dtype)
print("Item Size:", arr1.itemsize)

Dimensions: 1
Shape: (10,)
Size: 10
Data Type: int64
Item Size: 8


In [22]:
# For 2D array

print("Dimensions:", arr2.ndim)
print("Shape:", arr2.shape)
print("Size:", arr2.size)
print("Data Type:", arr2.dtype)
print("Item Size:", arr2.itemsize)


Dimensions: 2
Shape: (3, 3)
Size: 9
Data Type: int64
Item Size: 8


3. Converting float array to integer

In [35]:
float_arr = np.array([[1.1, 2.2, 3.3],
                      [4.4, 5.5, 6.6],
                      [7.7, 8.8, 9.9]])

print("Float Array:")
print(float_arr)

int_arr = float_arr.astype(int)

print("----------------------------")
print("Converted Integer Array:")
print(int_arr)


Float Array:
[[1.1 2.2 3.3]
 [4.4 5.5 6.6]
 [7.7 8.8 9.9]]
----------------------------
Converted Integer Array:
[[1 2 3]
 [4 5 6]
 [7 8 9]]
